# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAccounts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('twitter_id', models.BigIntegerField(unique=True)),
                ('oauth_token', models.CharField(max_length=60)),
                ('oauth_secret', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'twitter_accounts',
            },
        ),
    ]
